import { Component } from '@angular/core';
import { NavController} from 'ionic-angular';
import{ HtmlkonuanlatimPage} from '../htmlkonuanlatim/htmlkonuanlatim';
@Component({
  selector: 'page-list',
  templateUrl: 'list.html'
})
export class ListPage {
  rootPage :any=ListPage;
  public konu_basliklar:any;
  constructor(public navCtrl: NavController) {
    // If we navigated to this page, we will have an item available as a nav param
    this.konu_basliklar = [
      { baslik2: 'Html Nedir',
        icerik2:'Html web sayfaları hazırlamak için kullanılan bir işaretleme dilidir.Halihazırda kullandığımız web tarayıcıları (Internet Explorer, Firefox, Chrome v.b) bu kodları anlayarak görsel web sayfalarına dönüştürürler. Html bir programlama dili değildir.Html ile web sayfası hazırlamak için bilgisayarınıza herhangi bir program yüklemenize gerek yoktur. Herhangi bir metin editörü (not defteri, word, wordpad gibi) html sayfaları oluşturmak için yeterlidir. Fakat kodları yazarken kolaylık sağlamak ve kod yazım hızını arttırmak için Dreamweaver, Notepad++, Sublime Text gibi programlar tercih edilebilir.Hazırlamış olduğunuz web sayfalarını kaydederken html, htm, xhtml gibi tarayıcıların anlayabileceği bir uzantı ile kaydetmeniz gerekir.İlk kodumuzu Yazalım;', 
        icerik3:"<html><head><title>Hoşgeldiniz</title></head><body><p>Html Öğreniyorum</p></body></html>",
        component: HtmlkonuanlatimPage},
      { baslik2: 'Html Metin Biçimlendirme',
        icerik2:'1) <h> Başlık Etiketi: Bu etiket yazılara başlık eklemek için kullanılır.Farklı büyüklükte başlıklar kullanılabileceği için h1, h2, h3, h4, h5, h6 olmak üzere 6 farklı başlık büyüklüğü mevcuttur. Burada en büyük başlık <h1> en küçük ise <h6> dır. ', 
        icerik3:"2.)<b> Kalınlık Etiketi: Bu etiket yazıları kalın yapmak için kullanılır.  <b>Bu metin kalın olarak yazıldı.</b> Sadece bu kısım <b>kalın</b> yazıldı .3.)<i> İtalik (eğik yazı) Etiketi: Bu etiket metni eğik yazmak için kullanılır.4.) <u> Altını Çiz etiketi: Bu etiket metnin istenen kısımlarının altını çizmek için kullanılır. <u> Bu yazının altı çizilidir.</u> 5.)<br> Alt Satıra Geç Etiketi: Html dili ile web sitesi oluştururken bir alt satıra geçmek için Enter tuşunun işe yaramadığını görürsünüz. Html’de alt satıra geçmek için <br> etiketi kullanılır. Bu etiket kapatılmaz.6) <p>Paragraf Etiketi: Yazdığımız metini paragraflara bölmek için kullanılır. Uzun yazılarda okunabilirliği arttırır.7) <font> Etiketi: Font etiketi metin rengini ayarlama, yazı tipini değiştirme ve boyutunu ayarlamak için kullanılır. Tek bir etiketin bu 3 özelliği değiştirebilmesi aldığı parametreler sayesinde olmaktadır.Size parametresi: Metnin boyutunu ayarlamak için kullanılır. Yazının büyüklüğü 1 ile 7 arasında değer alır .<font size='4'>Metnin boyutunu değiştiriyorum.</font>   Face parametresi: Yazı tipini değiştirmek için kullanılır. <font face='Arial'> Bu metin Arial fontuyla yazıldı.</font> Color parametresi: Yazı rengini değiştirmek için kullanılır. Red, blue, yellow gibi renklerin ingilizcesi kullanılabileceği gibi #3b457c gibi renk kodlarıda kullanılabilir. <font color='red'> Bu metin kırmızı renklidir.</font>",
        component:HtmlkonuanlatimPage},
      { baslik2: 'Html Temel Etiketleri', 
        icerik2:"1.)<html>,<head>,<body> gibi büyüktür (<…>) içerisine yazılan kodlara etiket (tag) adı verilir.2.) Açılan her etiket kapatılır.Etiketi kapatmak için / işareti kullanılır.3.) Html etiketlerinde Türkçe karakterler yer almaz.4.)Etiketler büyük veya küçük harfle yazılabilir. Fakat genel kabul görmüş yazım biçimi küçük harftir.",
        icerik3:"Html: Bu etiket diğer tüm etiketleri sarmalayan html diliyle kodlama yapılacağını belirten, sayfanın başında açılıp sonunda kapatılan bir etikettir. Head: Hazırladığımız sayfa ile ilgili bilgiler ve tanımlamaların yer aldığı bloktur. Bu kısımdaki kodlar web sayfasında görüntülenmezler.Yukarıdaki kodda head etiketinin içerisinde <title> etiketi kullanılmıştır. Title web sayfasının başlığı anlamına gelmektedir. Hazırladığınız sayfayı incelediğinizde web sayfanızın üst sekmesinde Hoşgeldiniz yazısını görebilirsiniz.Body: Bu etiket ziyaretçinin görebildiği, sayfanın tüm içeriğinin yer aldığı bölümdür. Kullanılacak etiketlerin bir çoğu body etiketinin içerisinde yer alır.",
        component: HtmlkonuanlatimPage},
      { baslik2: 'Ol Etiketi İle Liste Oluşturma',
        icerik2:'Listeleme etiketleri derken kelime işlemci programlarında aşina olduğunuz sıralı liste ve madde işaretli listeler htmlde de sıklıkla kullanılır. Bu etiketler verilerin düzgün şekilde gösterilmesinin yanında her türlü menünün (yatay,dikey ve açılır menü) yapısında da temel taş olarak yer alırlar.',
        icerik3:"<ol> :Ordered (sıralı) liste oluşturmak için kullanılır. Alt alta başında 1,2,3 olacak şekilde liste elemanlarını  sıralar. type parametresi: Listeleme etiketinin türünü değiştirir. <ol type=”A”> şeklinde bir kullanımda 1,2,3 yerine A,B,C yazılır. A, alfabetik bir liste oluşturur. Küçük harfi de kullanılabilir. I, roma rakamı ile liste oluşturur.Küçük harfide kullanılabilir.", 
        component: HtmlkonuanlatimPage},
      { baslik2: 'Ul Etiketi İle Liste Oluşturma', 
        icerik2:'<ul> :Unordered (sırasız) liste oluşturmak için kullanılır. Alt alta başında madde işaretleri olacak şekilde.<li> :Listenin her bir öğesini oluşturmak için kullanılır.',
        icerik3:"<p>Sebzeler</p><ul><li>Kabak</li><li>Marul</li><li>Lahana</li><li>Domates</li></ul> <ul type=”square”> şeklinde bir kullanımda madde işaretleri kare şeklinde görülür.square: kare şeklinde liste oluşturur.circle: içi boş daire şeklinde liste oluşturur. disc: içi dolu daire şeklinde liste oluşturur.", 
        component: HtmlkonuanlatimPage},
      { baslik2: 'A Etiketi İle Link Oluşturma', 
        icerik2:'HTML başka bir dökümana link oluşturmak için <a> etiketini kullanır.Kullanım biçimi:<a href="url">Görüntülenecek Metin</a>Bir örnek:<a href="www.htmldersleri.org">Kodlayın, Tıklayın, Görün...</a>',
        icerik3:"Target parametresi ile dökümanın nerde açılacağını belirtebilirsiniz.Aşağıdaki bağlantıya tıklanırsa, döküman yeni bir pencerede açılacaktır.<a href='www.htmldersleri.org' target='_blank2'>Kodlayın,Tıklayın, Görün...</a> <a> Etiketi ve Name Parametresi Bu parametre ile aynı döküman içinde belirlenmiş başka bir satıra direkt geçiş yapılabilir.Kullanım Biçimi:<a name='label'> Görüntülenecek Metin</a> The name attribute is used to create a named anchor. The name of the anchor can be any text you care to use. Bir Örnek: <a name='ipucu'>Yararlı Bilgiler</a>",
        component: HtmlkonuanlatimPage},
      { baslik2: 'Tablo Oluşturma',
        icerik2:'Table etiketi: Bir tablo oluşturmak için gerekli kodların tümü <table> ve </table> etiketleri arasına yazılır. Tablolar satır ve sütunlardan oluşur. Tr Etiketi: Tablo içerisinde satır oluşturmak için kullanılır. Bir satır <tr> ile başlar </tr> ile sona erer.Td Etiketi: Tablo içerisinde sütun oluşturmak için kullanılır. Bir sütun <td> ile başlar </td> ile sona erer. Th Etiketi: Tablo içerisindeki sütunlardan başlık olanları belirtmek için kullanılır.',
        icerik3:"border: kenarlık oluşturmak için kullanılır.bordercolor:kenarlıkların rengini değiştirmek için için kullanılır.bgcolor:tablonun arkaplan rengini değiştirmek için kullanılır.width:Tablonun genişliğini ayarlamak için kullanılır.height:Tablonun yüksekliğini ayarlamak için kullanılır.Yukarıda saydığım parametreler table etiketinin parametreleridir. Bu parametreleri aşağıdaki gibi kullanabilirsiniz.<table border=”1″bordercolor=”red”width=”300px”height=”250px”bgcolor=”pink”>Satır ve Sütunları Birleştirmek Bazı durumlarda tablolarda ki satır ve sütunları birleştirmemiz gerekebilir. Bu durumda aşağıdaki parametreler kullanılır.colspan: Aynı satırdaki hücreleri birleştirmek için kullanılır.rowspan: Aynı sütundaki hücreleri birleştirmek için kullanılır.", 
        component: HtmlkonuanlatimPage},
      {  baslik2: 'Html Form Etiketleri', 
         icerik2:'Basit bir form oluşturma Bütün form öğeleri mutlaka <form> ….</form> öğeleri arasına yazılır.Action parametresi: form öğesinin olmazsa olmaz parametrelerinden biridir. Kullanıcının girdiği verilerin hangi sayfada işleneceğini gösterir. Örneğin çift tırnak arasına kayit.php yazılırsa girilen veriler bu sayfada işlenmek için oraya postalanır.Method parametresi: Verilerin postalanma biçimini belirtmek için kullanılır. Genellikle get veya post parametreleri kullanılır. Örneğin get ile bir arama yaptığınızda adres çubuğunda aramanızla ilgili bilgilerin yer aldığını görürsünüz. Bu nedenle şifre gibi gizli bilgiler bu metotla kullanılmaz. Post ise daha güvenli bir veri gönderim tekniğidir.',
         icerik3:"Input Text: Bu klasik içerisine bir şeyler yazmamızı sağlayan dikdörtgen şeklindeki form öğesidir. Metin kutusu, textbox veya textfield diye adlandırabiliriz.Adınız:<input type='text' name='txtIsim'> Input Submit: Bu kontrol öğesi girilen verileri form action ve post öğesinde belirtilen yere göndermeye yarar. <input type='submit' name='btnGonder'> Input Password:Şifrelerinizi girerken bunları gizleyerek ekrana bakan kişilerden gizleyen, text öğesinin benzeri bir kontroldür.Şifreniz:<input type='password' name='txtŞifre'> Input radio: Radio öğesi birden fazla seçenek arasından bir tanesini seçmek için kullanılır. Dikkat etmeniz gereken kısım ilişkili radio öğelerinin adları aynı olmalıdır.Cinsiyetiniz:<input type='radio'name='cinsiyet'>Erkek Input Checkbox: Checkbox birden fazla seçenek arasından bir veya daha fazlasını seçmek için kullanılır. Örnek olarak dilleri verdim. Bir kişi birden fazla dil bilebilir. Bildiğiniz Diller:<input type='checkbox'name='dil1'>İngilizce <input type='checkbox' name='dil2'>Almanca Select: Önceden tanımlanmış seçenekler arasından bir tanesini seçmek için kullanılır. Örnek olarak yaşadığınız il güzel bir örnek.Yaşadığınız İl:<select> <option>İstanbul</option> <option>Ankara</option> <option>İzmir</option> </select>  7- Textarea: Text kutusunun daha büyük ve çok satırlı biçimidir. Satır ve sütün sayısı değiştirilerek büyüklüğü ayarlanabilir.Adresiniz:<textarea rows='5'cols='30'></textarea>8-Input reset: Bu kontrol ise formu göndermek için değil içerisindeki verileri temizlemek için kullanılır. <input type='reset' name='btnTemizle' value='Temizle'>",
         component: HtmlkonuanlatimPage},
      {  baslik2: 'Resim ,Ses Ve Video Ekleme',
         icerik2:'Bir HTML sayfasına dosyadan video eklemek için <video> etiketi kullanılır.<video> Etiketi Yardımcı Elemanlar controls : Video denetim elemanlarının (örneğin play / pause düğmeleri vb) görüntülenmesi sağlar.autoplay :İlgili sayfaya girildiğinde videoyu otomatik olarak başlatılmasını sağlar.src=" hedef video URL " Oynatılacak videonun dosya hedefini belirler. height=" sayı " Video penceresinin yüksekliğini belirler. width="sayı" Video penceresinin genişliğini belirler.<video width="320" height="240" controls autoplay src="video/loca.mp4"> </video>',
         icerik3:"Siteye Ses Dosyası Ekleme <audio controls> <source src='horse.ogg' type='audio/ogg'> <source src='horse.mp3' type='audio/mpeg'> Tarayıcınız audio elementini desteklemiyor. </audio> control özelliği; play, pause, ses gibi denetimleri ekler. Ayrıca <audio> ve </audio> etiketleri arasına desteklemeyen tarayıcı uyarısı eklemek zorundasınız.<audio> elementi çoklu kaynak (<source>) kullanımına izin verir. <source> elementi farklı ses dosyalarına bağlantıya izin verir. Tarayıcı, ilk tanımlayabildiği dosyayı kullanır.Web Sayfasına Resim Ekleme", 
         component: HtmlkonuanlatimPage},
      {  baslik2: 'Temel Css İşlemleri 1',
         icerik2:'CSS Nedir HTML bize metin biçimlendirme alanında çok geniş olanaklar sunar. CSS, uzun yazılışıyla Cascading Style Sheets, veya Türkçesiyle Stil şablonları ise bunu bir adım daha öteye götürür, bize sayfalarımız için global şablonlar hazırlama olanağı verdiği gibi, tek bir harfin stilini; yani renk, font, büyüklük gibi özelliklerini değiştirmek için de kullanılabilir. Bu tekniğin en önemli özelliği kullanımındaki bu esnekliğidir.CSS kodları HTML kodlarının içine yazılırlar. Türüne göre body veya head bölümlerinde yer alabilirler. Bunların dışında harici CSS dosyaları oluşturulup bunlar gerektiğinde HTML belgesi içerisinde çağırılabilirler. ',
         icerik3:"Genel CSS ; Belirli bir sayfanın <head> bölümüne yerleştirilir. Sınıflar(class) ve kimlikler(id), CSS kodunu belirtmek için kullanılabilir, ancak genel css yalnızca eklendiği belirli sayfada etkindir.Genel css , <style type='text/css'> </style> etiketlerinin arasına yerleştirilir.Harici CSS Muhtemelen web sitenize CSS eklemenin en uygun yolu, onu harici bir style.css dosyasına bağlamaktır.Harici css dosyanızı bu şekilde sayfanıza ekleyebilirsiniz.<head><link rel='stylesheet' type='text/css' href='style.css' /></head> Yerel CSS; Belirli bir HTML etiketi için kullanılır. <style> özniteliği, belirli bir HTML etiketini stillemek için kullanılır. <body style='background-color:black; CSS Seçiciler: Etiketlerimize genel veya harici olarak css özelliği verebilmemiz için mutlaka id veya class ismi oluşturması gerekilir.ID classlardan simgesel olarakda ayrılmaktadır.ID lerde '#' kullanılırken classlarda '. 'kullanılmaktadır.Sayfadaki Hali:<div id='menu'>İd örneği</div> Style Hali: #menu{background-color: red} ; Sayfadaki Hali:<div class='menu'>İd örneği </div> Style Hali: .menu{background-color: red} .Bu seçiciler <style></style> etiketleri içerisinde yazılır. ",
         component: HtmlkonuanlatimPage},
      {  baslik2: 'Temel Css İşlemleri 2', 
         icerik2:'LİNK ÖZELLİKLERİ ->> a: Linkin, sayfa açıldığında tıklanmadan veya ümleç üzerine getirilmeden önceki durumudur. a:hover : Linkin imleç üzerine getirildiğindeki durumudur. a:active : Linkin tıklandığı andaki durumudur. a:visited : Linkin tıklandıktan sonraki durumudur. BİÇİMLENDİRME; color: Linkin rengini belirler. background-color: Linkin zemin rengini belirler.background-image: Linkin zeminine resim ekler(Bu animated-gif de olabilir.) text-decoration: Linkin altının,üstünün vs. çizgili olup olmayacağını belirler. font-weight: Yazının kalınlık veya inceliğini belirler.border: Linkin etrafına kenarlık ekler. display: Linki içeren hücre , satır vb. istenilen alanın seçilmesini sağlar.KATMAN ÖZELLİKLERİ->>position: Katmanın yerinin belirlenmesini sağlar.absolute: Katmanın yerinin pencere esas alınarak belirlenmesini sağlar.relative: Katmanın yerinin bir önceki katman esas alınarak belirlenmesini sağlar.static: Katmanın yerinin sabit olarak (Varsayılan olan sol üst köşe) belirlenmesini sağlar.top: Katmanın üstten ne kadar aşağıda olması gerektiğini belirler.left: Katmanın soldan ne kadar içeride olması gerektiğini belirler.width: Katmanın genişliğinin ne kadar olacağını belirler.height: Katmanın yüksekliğinin ne kadar olacağını belirler.overflow: Katmanın belirtilen yükseklik ve genişliğe sığmayan kısmına ne olacağını belirler.auto: Otomatik olarak belirlenir.scroll: Kaydırma çubuğu ekleyerek görünmesini sağlar.visible : Katmanı belirtilen boyutların dışına taşırarak sığmayan yerlerin görünmesini sağlar.hidden: Sığmayan yerleri gizler.visibility: Katmanın görünebilirlik ayarını yapar.visible : Katmanın görünür olmasını sağlar.hidden: Katmanı gizler.z-index : Katmanların alttan üste doğru hangi sıra ile gösterileceğini belirler.1 değeri katmanın en altta olacağını belirtir.',
         icerik3:"TEXT ÖZELLİKLERİ->>word-spacing : Kelimeler arasında bırakılacak boşluğu boşluğu belirler.letter-spacing : Harfler arasında bırakılacak boşluğu boşluğu belirler.text-decoration : Kelimenin altının , üstünün vs. çizili olup olmayacağını belirler.underline : Kelimenin altının (Satır altından) çizili olmasını sağlar.overline : Kelimenin üstünün (Satır üstünden) çizili olmasını sağlar.line-through : Kelimenin ortasından çizili olmasını sağlar.blink : Kelimenin yanıp sönmesini sağlar.(Netscape için)vertical-align : Metnin yatay olarak nasıl hizalanacağını belirler.text-transform: Kelimelerin büyük harf veya küçük harflerden oluşmasını sağlar.capitalize : Kelimelerin ilk harflerinin büyük olmasını sağlar.uppercase : Kelimelerin bütün harflerinin büyük olmasını sağlar.lowercase : Kelimelerin bütün harflerinin küçük olmasını sağlar.none : Kelimelerin orjinal metindeki gibi olmasını sağlar.text-align: Metnin dikey olarak nasıl hizalanacağını belirler.left : Metni sola yaslar.right : Metni sağa yaslar.center : Metni ortalar.justify : Metni iki yana yaslar.text-indent : Metnin ilk satırının soldan ne kadar içerden başlayacağını belirler.line-height : Satırın yüksekliğini ayarlar.(Yüksek değer verildiğinde satırlar arasındaki boşluk artar.)first-line : Metnin ilk satırının biçimlendirilmesini sağlar.first-letter : Metnin ilk harfinin biçimlendirilmesini sağlar.",
         component: HtmlkonuanlatimPage},
      {  baslik2: 'Temel Css İşlemleri 3', 
         icerik2:'ZEMİN ÖZELLİKLERİ->> background-color: Zeminin rengini belirler. #color : Renk adı.transparent: Zeminin saydam olmasını sağlar.background-image: Zemine resim yerleştirilmesini sağlar.url : Zemine yerleştirilen resmin adresi.background-repeat: Zemine yerleştirilen resmin nasıl yayılacağını belirler. repeat : Resmin bütün zemine yayılmasını sağlar.repeat-x : Resmin sol-üstten sağ-üste doğru yayılmasını sağlar.repeat-y : Resmin sol-üstten sol-alta doğru yayılmasını sağlar.no-repeat: Resmin yayılmadan orjinal boyutuyla görünmesini sağlar. background-attachment: Zemindeki resmin , sayfa kaydırma çubuğuyla hareket ettirildiğindeki durumunu belirler.scroll : Sayfa hareket ettirildiğinde zeminin de kaymasını sağlar.fixed: Sayfa kaydırılsa da zeminin sabit kalmasını sağlar. background-position: Zemindeki resmin istenilen şekilde yerleştirilmesini sağlar. top : Resmi yukarı yerleştirir.center : Resmi ortalar.bottom : Resmi aşağı yerleştirir. left : Resmi sola yerleştirir.right: Resmi sağa yerleştirir.',
         icerik3:"TABLO ÖZELLİKLERİ->> margin : Tablo ile pencerenin kenarları arasında bırakılacak boşluğu belirler.padding : Tablo kenarları ile tablo içeriği (Yazı vb.) arasında bırakılacak boşluğu belirler.border : Tablonun kenarlarının şekillendirilmesini sağlar.border-width : Tablonun kenarlarının kalınlığını belirler.border-style : Tablonun kenarlık türünü belirler.Solid ,düz çizgidir.Dashed kesikli çizgidir.border-color : Tablonun kenarlarının rengini belirler.",
          component: HtmlkonuanlatimPage}
    ];
 
  }
  gokonular(sayfa:string) {
    this.navCtrl.push(HtmlkonuanlatimPage,{
      data2:sayfa
    })
  }
}
